### ISSUE TITLE
Boat duplication and everything broke

### ISSUE THREAD

**Issue by theanalstoveSleepmode** [Woukie/The-Boat-Mod#1]
I left the world yesterday and went to sleep. today when I entered the world I had two boats one inside the other 
And nothing worked 
video : https://drive.google.com/file/d/1-1-dBuDFmZ6bjRwZe-eA7yZ69prTJGNA/view?usp=sharing

**Comment by Woukie** [comment]
No idea what causes this yet, sorry this happened to you, the current solution is to delete the build at the red computer. You will get all your blocks back, and coins will stay, but your build will get deleted.

Also thanks for submitting the video, helps me greatly!
